- hosts: all
  name: Setup development environment
  sudo: yes
  tasks:
    - apt: name="{{item}}" state=present
      with_items:
        - geany
        - mono-complete
        - git
        - gitg
        - chromium-browser
        - virtualbox
        - vagrant
        - npm
        - php5-cli
        
    - file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

    - name: install Composer
      shell: php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: install Bower
      shell: npm install -g bower
      args:
        creates: /usr/local/bin/bower
