- hosts: all
  name: Setup xForge development environment
  sudo: yes
#  roles:
#    - apache_config
  tasks:
    - apt: name="{{item}}" state=present
      with_items:
        - geany
        - git
        - gitg
        - chromium-browser
        - npm
        - php5-cli
        - eclipse
        
    - name: install Composer
      shell: php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: install Bower
      shell: npm install -g bower
      args:
        creates: /usr/local/bin/bower
    
    - file: src=/usr/bin/nodejs dest=/usr/local/bin/node state=link

